version: '3'
services:
  flask-login:
    container_name: flask-login
    build:
      context: ./
    volumes:
      - ./:/mnt/flask_login/
    ports:
      - 5000:5000
    command: >
      bash -c "python microblog.py"
networks:
  default:
    external:
      name: fratment
#for test
